from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 423)
        MainWindow.setMinimumSize(QtCore.QSize(378, 423))
        MainWindow.setMaximumSize(QtCore.QSize(378, 423))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ID_Input = QtWidgets.QLineEdit(self.centralwidget)
        self.ID_Input.setGeometry(QtCore.QRect(80, 60, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ID_Input.setFont(font)
        self.ID_Input.setObjectName("ID_Input")
        self.ID_Label = QtWidgets.QLabel(self.centralwidget)
        self.ID_Label.setGeometry(QtCore.QRect(40, 60, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ID_Label.setFont(font)
        self.ID_Label.setObjectName("ID_Label")
        self.Title_Label = QtWidgets.QLabel(self.centralwidget)
        self.Title_Label.setGeometry(QtCore.QRect(90, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Title_Label.setFont(font)
        self.Title_Label.setObjectName("Title_Label")
        self.Candidates_Label = QtWidgets.QLabel(self.centralwidget)
        self.Candidates_Label.setGeometry(QtCore.QRect(120, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Candidates_Label.setFont(font)
        self.Candidates_Label.setObjectName("Candidates_Label")
        self.John_Radio = QtWidgets.QRadioButton(self.centralwidget)
        self.John_Radio.setGeometry(QtCore.QRect(150, 160, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.John_Radio.setFont(font)
        self.John_Radio.setObjectName("John_Radio")
        self.Jane_Radio = QtWidgets.QRadioButton(self.centralwidget)
        self.Jane_Radio.setGeometry(QtCore.QRect(150, 200, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Jane_Radio.setFont(font)
        self.Jane_Radio.setObjectName("Jane_Radio")
        self.Submit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Submit_Button.setGeometry(QtCore.QRect(90, 260, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Submit_Button.setFont(font)
        self.Submit_Button.setObjectName("Submit_Button")
        self.Error_Label = QtWidgets.QLabel(self.centralwidget)
        self.Error_Label.setGeometry(QtCore.QRect(120, 330, 141, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.Error_Label.setFont(font)
        self.Error_Label.setObjectName("Error_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ID_Label.setText(_translate("MainWindow", "ID"))
        self.Title_Label.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.Candidates_Label.setText(_translate("MainWindow", "CANDIDATES"))
        self.John_Radio.setText(_translate("MainWindow", "John"))
        self.Jane_Radio.setText(_translate("MainWindow", "Jane"))
        self.Submit_Button.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.Error_Label.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
